modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="towny"
version="1.0.0"
displayName="NeoTowny"
description='A NeoForge port of the Towny Bukkit plugin with Lightmans Currency integration.'
logoFile="icon.png"
credits=""
authors="Baldeagle"

[[dependencies.towny]]
modId="neoforge"
type="required"
versionRange="[21.1.228,)"
ordering="NONE"
side="BOTH"

[[dependencies.towny]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
